spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: postgres
    password: kotreyjr10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or your desired value (create, create-drop, none)
    show-sql: true # Set to true to see SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect